services:
  comfy-ui:
    build:
      context: /docker
      args:
          - IMAGE_VERSION
          - COMFYUI_VERSION
          - COMFYUI_MANAGER_VERSION
    ports:
      - "${HTTP_PORT:-8188}:8188"
    volumes:
      - models:/comfyUI/models
      - custom-nodes:/comfyUI/custom_nodes
      - ./data/outputs:/comfyUI/output
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                count: all
                capabilities: [compute, utility]
volumes:
  models:
  custom-nodes:
